// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCt7b2feRsWG7auqWB7SJsJQN65ftv1pUc',
    appId: '1:396885867236:web:ffa7611a945fe29900caf1',
    messagingSenderId: '396885867236',
    projectId: 'comfort-care-web-site',
    authDomain: 'comfort-care-web-site.firebaseapp.com',
    storageBucket: 'comfort-care-web-site.appspot.com',
    measurementId: 'G-Z1BL0XTP7X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDipZ8SMVoM18FeywRyFDlmi41Dq944YEQ',
    appId: '1:396885867236:android:4938db8aaf94982600caf1',
    messagingSenderId: '396885867236',
    projectId: 'comfort-care-web-site',
    storageBucket: 'comfort-care-web-site.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTSlyO_xHtq3_dobfsunhn2vmJPLXK18I',
    appId: '1:396885867236:ios:1fb901051bda312300caf1',
    messagingSenderId: '396885867236',
    projectId: 'comfort-care-web-site',
    storageBucket: 'comfort-care-web-site.appspot.com',
    iosBundleId: 'com.example.confirtCare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTSlyO_xHtq3_dobfsunhn2vmJPLXK18I',
    appId: '1:396885867236:ios:1fb901051bda312300caf1',
    messagingSenderId: '396885867236',
    projectId: 'comfort-care-web-site',
    storageBucket: 'comfort-care-web-site.appspot.com',
    iosBundleId: 'com.example.confirtCare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCt7b2feRsWG7auqWB7SJsJQN65ftv1pUc',
    appId: '1:396885867236:web:ee59cf51b6d69ff300caf1',
    messagingSenderId: '396885867236',
    projectId: 'comfort-care-web-site',
    authDomain: 'comfort-care-web-site.firebaseapp.com',
    storageBucket: 'comfort-care-web-site.appspot.com',
    measurementId: 'G-G0KBJM5DVS',
  );

}